version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat/webapps
permissions:
   - object: /opt/tomcat/webapps
     pattern: "**"
     owner: tomcat
     group: tomcat
     mode: 755
     type:
       - file	
hooks:
  BeforeInstall:
    - location: scripts/stoptomcat.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restarttomcat.sh
      timeout: 300
      runas: root